RULE_PRIMITIVE_MAP = {

    # ========== dm_date (DTC1, 17 rules) ==========
    "SD0087": {"primitive": "blank_field", "params": {"field": "RFSTDTC"},
               "domain": "DM", "guard": "ARMCD not in (SCRNFAIL,NOTASSGN,)",
               "co_violations": ["SD1085", "SD1086"]},
    "SD0088": {"primitive": "blank_field", "params": {"field": "RFENDTC"},
               "domain": "DM", "guard": "ARMCD not in (SCRNFAIL,NOTASSGN,)"},
    "SD1002": {"primitive": "invert_date_order",
               "params": {"start_field": "RFSTDTC", "end_field": "RFENDTC"},
               "domain": "DM"},
    "SD1208": {"primitive": "cross_domain_mismatch",
               "params": {"source": "DM", "source_field": "RFXSTDTC",
                          "target": "EX", "target_field": "EXSTDTC",
                          "mismatch_type": "not_equal_min"},
               "domain": "DM"},
    "SD1258": {"primitive": "populate_forbidden",
               "params": {"field": "RFSTDTC", "value": "2024-01-01"},
               "domain": "DM", "guard": "ARMCD in (SCRNFAIL,NOTASSGN,)"},
    "SD1342": {"primitive": "blank_field", "params": {"field": "RFXSTDTC"},
               "domain": "DM", "guard": "ARMCD not in (SCRNFAIL,NOTASSGN,)"},
    "SD1343": {"primitive": "blank_field", "params": {"field": "RFXENDTC"},
               "domain": "DM", "guard": "ARMCD not in (SCRNFAIL,NOTASSGN,)"},
    "SD2004": {"primitive": "blank_field", "params": {"field": "DTHDTC"},
               "domain": "DM", "guard": "DTHFL == Y"},
    "SD2005": {"primitive": "populate_forbidden",
               "params": {"field": "DTHFL", "value": "Y"},
               "domain": "DM", "guard": "DTHDTC == "},
    "SD1209": {"primitive": "blank_field", "params": {"field": "RFXENDTC"},
               "domain": "DM", "guard": "RFXSTDTC != "},
    "SD1210": {"primitive": "blank_field", "params": {"field": "RFICDTC"},
               "domain": "DM"},
    "SD1213": {"primitive": "blank_field", "params": {"field": "RFSTDTC"},
               "domain": "DM", "guard": "ACTARMCD not in (SCRNFAIL,NOTASSGN,NOTTRT,)"},
    "SD1259": {"primitive": "set_invalid_value",
               "params": {"field": "SETCD", "value": "INVALID_SETCD_VALUE"},
               "domain": "DM"},
    "SD1334": {"primitive": "invert_date_order",
               "params": {"start_field": "RFICDTC", "end_field": "RFSTDTC"},
               "domain": "DM"},
    "SD1335": {"primitive": "invert_date_order",
               "params": {"start_field": "RFICDTC", "end_field": "RFXSTDTC"},
               "domain": "DM"},
    "SD1366": {"primitive": "populate_forbidden",
               "params": {"field": "RFENDTC", "value": "2024-12-31"},
               "domain": "DM", "guard": "ARMNRS != "},
    "SD1376": {"primitive": "blank_field", "params": {"field": "RFENDTC"},
               "domain": "DM", "guard": "ACTARMCD not in (SCRNFAIL,NOTASSGN,NOTTRT,)"},
    "SD2023": {"primitive": "blank_field", "params": {"field": "AGE"},
               "domain": "DM"},

    # ========== date_cross_domain (DTC2, 7 rules) ==========
    "SD0013": {"primitive": "invert_date_order",
               "params": {"start_field": "--STDTC", "end_field": "--ENDTC"},
               "domain": "--"},
    "SD0038": {"primitive": "set_invalid_value",
               "params": {"field": "--DY", "value": "0"},
               "domain": "--"},
    "SD1085": {"primitive": "truncate_with_derived",
               "params": {"date_field": "--DTC", "dy_field": "--DY"},
               "domain": "--"},
    "SD1086": {"primitive": "wrong_derived",
               "params": {"field": "--DY", "offset_range": [-10, 10]},
               "domain": "--"},
    "SD1202": {"primitive": "cross_domain_mismatch",
               "params": {"source_field": "--STDTC", "target": "DM",
                          "target_field": "RFPENDTC", "mismatch_type": "date_after"},
               "domain": "--"},
    "SD1203": {"primitive": "cross_domain_mismatch",
               "params": {"source_field": "--DTC", "target": "DM",
                          "target_field": "RFPENDTC", "mismatch_type": "date_after"},
               "domain": "--"},
    "SD1204": {"primitive": "cross_domain_mismatch",
               "params": {"source_field": "--ENDTC", "target": "DM",
                          "target_field": "RFPENDTC", "mismatch_type": "date_after"},
               "domain": "--"},

    # ========== age_arm (DM01, 21 rules) ==========
    "SD0084": {"primitive": "set_invalid_value", "params": {"field": "AGE", "value": "0"},
               "domain": "DM"},
    "SD0093": {"primitive": "blank_field", "params": {"field": "AGEU"},
               "domain": "DM", "guard": "AGE != "},
    "SD1001": {"primitive": "duplicate_record",
               "params": {"key_fields": ["STUDYID", "SUBJID"]}, "domain": "DM"},
    "SD1003": {"primitive": "blank_field", "params": {"field": "AGE"},
               "domain": "DM", "guard": "AGEU != "},
    "SD1121": {"primitive": "blank_field", "params": {"field": "AGE"},
               "domain": "DM"},
    "SD1133": {"primitive": "mismatch_pair",
               "params": {"field_a": "ACTARMCD", "field_b": "ACTARM"}, "domain": "DM"},
    "SD1134": {"primitive": "mismatch_pair",
               "params": {"field_a": "ACTARM", "field_b": "ACTARMCD"}, "domain": "DM"},
    "SD0011": {"primitive": "mismatch_pair",
               "params": {"field_a": "ARMCD", "field_b": "ARM",
                          "expected": {"SCRNFAIL": "Screen Failure"}},
               "domain": "DM", "guard": "ARMCD == SCRNFAIL"},
    "SD0053": {"primitive": "mismatch_pair",
               "params": {"field_a": "ARMCD", "field_b": "ARM",
                          "expected": {"NOTASSGN": "Not Assigned"}},
               "domain": "DM", "guard": "ARMCD == NOTASSGN"},
    "SD1322": {"primitive": "invalid_codelist",
               "params": {"field": "COUNTRY", "valid_values": ["USA", "GBR", "DEU", "FRA", "JPN"]},
               "domain": "DM"},
    "SD1349": {"primitive": "set_invalid_value",
               "params": {"field": "STUDYID", "value": "WRONG_STUDY_ID"},
               "domain": "DM"},
    "SD1358": {"primitive": "blank_field", "params": {"field": "ARMNRS"},
               "domain": "DM", "guard": "ACTARMCD == "},
    "SD1359": {"primitive": "blank_field", "params": {"field": "ARMNRS"},
               "domain": "DM", "guard": "ARMCD == "},
    "SD1360": {"primitive": "populate_forbidden",
               "params": {"field": "ARMNRS", "value": "INFORMED CONSENT WITHDRAWAL"},
               "domain": "DM", "guard": "ARMCD != "},
    "SD1361": {"primitive": "mismatch_pair",
               "params": {"field_a": "ARM", "field_b": "ARMCD"}, "domain": "DM"},
    "SD1362": {"primitive": "mismatch_pair",
               "params": {"field_a": "ACTARM", "field_b": "ACTARMCD"}, "domain": "DM"},
    "SD1363": {"primitive": "populate_forbidden",
               "params": {"field": "ARMCD", "value": "ACTIVE"},
               "domain": "DM", "guard": "ARMNRS != "},
    "SD1364": {"primitive": "populate_forbidden",
               "params": {"field": "ACTARMCD", "value": "ACTIVE"},
               "domain": "DM", "guard": "ARMNRS != "},
    "SD2001": {"primitive": "set_invalid_value",
               "params": {"field": "ACTARMCD", "value": "INVALID_ARMCD_VALUE"},
               "domain": "DM"},
    "SD2019": {"primitive": "set_invalid_value",
               "params": {"field": "AGETXT", "value": "BADFORMAT"},
               "domain": "DM"},
    "SD2020": {"primitive": "populate_forbidden",
               "params": {"field": "AGETXT", "value": "18-65"},
               "domain": "DM", "guard": "AGE != "},
    "SD2021": {"primitive": "blank_field", "params": {"field": "AGE"},
               "domain": "DM", "guard": "AGEU != "},
    "SD2022": {"primitive": "blank_field", "params": {"field": "AGEU"},
               "domain": "DM", "guard": "AGE != "},
    "SD2236": {"primitive": "mismatch_pair",
               "params": {"field_a": "ARMCD", "field_b": "ACTARMCD"}, "domain": "DM"},
    "SD2237": {"primitive": "mismatch_pair",
               "params": {"field_a": "ARM", "field_b": "ACTARM"}, "domain": "DM"},

    # ========== dm_cross_domain (DM02, 13 rules) ==========
    "SD0066": {"primitive": "cross_domain_mismatch",
               "params": {"source": "DM", "source_field": "ARMCD",
                          "target": "TA", "target_field": "ARMCD",
                          "mismatch_type": "not_in_set"},
               "domain": "DM", "guard": "ARMCD not in (SCRNFAIL,NOTASSGN,)"},
    "SD0069": {"primitive": "cross_domain_orphan",
               "params": {"source": "DM", "target": "DS", "key": "USUBJID"},
               "guard": "ARMCD not in (SCRNFAIL,NOTASSGN,)"},
    "SD0070": {"primitive": "cross_domain_orphan",
               "params": {"source": "DM", "target": "EX", "key": "USUBJID"},
               "guard": "ARMCD not in (SCRNFAIL,NOTASSGN,) and ACTARMCD != NOTTRT"},
    "SD0071": {"primitive": "cross_domain_mismatch",
               "params": {"source": "DM", "source_field": "ARMCD,ARM",
                          "target": "TA", "target_field": "ARMCD,ARM",
                          "mismatch_type": "combo_not_in_set"},
               "domain": "DM"},
    "SD0083": {"primitive": "duplicate_record",
               "params": {"key_fields": ["STUDYID", "USUBJID"]}, "domain": "DM"},
    "SD1004": {"primitive": "set_invalid_value",
               "params": {"field": "ARMCD", "value": "TOOLONGARMCODEVALUE12345"},
               "domain": "DM"},
    "SD1032": {"primitive": "cross_domain_orphan",
               "params": {"source": "DM", "target": "IE", "key": "USUBJID"},
               "guard": "ARMCD == SCRNFAIL"},
    "SD1240": {"primitive": "cross_domain_orphan",
               "params": {"source": "DM", "target": "DS", "key": "USUBJID"}},
    "SD1033": {"primitive": "mismatch_pair",
               "params": {"field_a": "ARMCD", "field_b": "ARM"}, "domain": "DM"},
    "SD1034": {"primitive": "mismatch_pair",
               "params": {"field_a": "ARM", "field_b": "ARMCD"}, "domain": "DM"},
    "SD1367": {"primitive": "duplicate_record",
               "params": {"key_fields": ["USUBJID", "DSSCAT", "EPOCH"]}, "domain": "DS"},
    "SD1374": {"primitive": "cross_domain_orphan",
               "params": {"source": "DM", "target": "DS", "key": "USUBJID"},
               "guard": "ACTARMCD not in (SCRNFAIL,NOTASSGN,NOTTRT,)"},
    "SD1377": {"primitive": "cross_domain_orphan",
               "params": {"source": "DM", "target": "IE", "key": "USUBJID"},
               "guard": "ARMNRS != "},
    "SD2002": {"primitive": "cross_domain_mismatch",
               "params": {"source": "DM", "source_field": "ACTARMCD",
                          "target": "TA", "target_field": "ARMCD",
                          "mismatch_type": "not_in_set"},
               "domain": "DM"},
    "SD2003": {"primitive": "cross_domain_mismatch",
               "params": {"source": "DM", "source_field": "ARMCD",
                          "target": "TA", "target_field": "ARM",
                          "mismatch_type": "combo_not_in_set"},
               "domain": "DM"},

    # ========== death_cascade (from EVT1, 9 rules) ==========
    "SD1254": {"primitive": "cross_domain_mismatch",
               "params": {"source": "AE", "source_field": "AEOUT",
                          "target": "DM", "target_field": "DTHFL",
                          "mismatch_type": "set_source_expect_target",
                          "source_value": "FATAL", "expected_target": "Y"},
               "domain": "AE"},
    "SD1255": {"primitive": "cross_domain_mismatch",
               "params": {"source": "AE", "source_field": "AESDTH",
                          "target": "DM", "target_field": "DTHFL",
                          "source_value": "Y", "expected_target": "Y"},
               "domain": "AE"},
    "SD1347": {"primitive": "cross_domain_mismatch",
               "params": {"source": "AE", "source_field": "AEENDTC",
                          "target": "DM", "target_field": "DTHDTC",
                          "mismatch_type": "not_equal"},
               "domain": "AE", "guard": "AEOUT == FATAL"},
    "SD1256": {"primitive": "cross_domain_mismatch",
               "params": {"source": "DS", "source_field": "DSDECOD",
                          "target": "DM", "target_field": "DTHFL",
                          "source_value": "DEATH", "expected_target": "Y"},
               "domain": "DS"},
    "SD1317": {"primitive": "cross_domain_mismatch",
               "params": {"source": "DS", "source_field": "DSSTDTC",
                          "target": "DM", "target_field": "DTHDTC",
                          "mismatch_type": "not_equal"},
               "domain": "DS", "guard": "DSDECOD == DEATH"},
    "SD1252": {"primitive": "cross_domain_mismatch",
               "params": {"source": "SS", "source_field": "SSSTRESC",
                          "target": "DM", "target_field": "DTHFL",
                          "source_value": "DEAD", "expected_target": "Y"},
               "domain": "SS"},
    "SD1316": {"primitive": "cross_domain_orphan",
               "params": {"source": "SS", "target": "DS", "key": "USUBJID"},
               "guard": "SSSTRESC == DEAD"},
    "SD1261": {"primitive": "cross_domain_mismatch",
               "params": {"source": "SS", "source_field": "SSDTC",
                          "target": "DM", "target_field": "DTHDTC",
                          "mismatch_type": "date_before"},
               "domain": "SS", "guard": "SSSTRESC == DEAD"},
    "SD1253": {"primitive": "cross_domain_mismatch",
               "params": {"source": "DD", "source_field": "USUBJID",
                          "target": "DM", "target_field": "DTHFL",
                          "mismatch_type": "absent"},
               "domain": "DD"},

    # ========== findings rules (FA1+FA2) ==========
    "SD0047": {"primitive": "blank_field", "params": {"field": "--ORRES"},
               "domain": "--", "guard": "--STAT != NOT DONE"},
    "SD0040": {"primitive": "populate_forbidden",
               "params": {"field": "--ORRES", "value": "999"},
               "domain": "--", "guard": "--STAT == NOT DONE"},
    "SD1137": {"primitive": "populate_forbidden",
               "params": {"field": "--DRVFL", "value": "Y"},
               "domain": "--", "guard": "--ORRES != "},
    "SD1138": {"primitive": "populate_forbidden",
               "params": {"field": "--DRVFL", "value": "Y"},
               "domain": "--", "guard": "--ORRES != "},
    "SD0007": {"primitive": "mismatch_pair",
               "params": {"field_a": "--TESTCD", "field_b": "--STRESU"},
               "domain": "--"},
    "SD0016": {"primitive": "blank_field", "params": {"field": "--STRESC"},
               "domain": "--", "guard": "--DRVFL == Y"},
    "SD0017": {"primitive": "set_invalid_value",
               "params": {"field": "--TEST", "value": "INVALID TEST LABEL VALUE 999"},
               "domain": "--"},
    "SD0018": {"primitive": "set_invalid_value",
               "params": {"field": "--TESTCD", "value": "INVTCD99"},
               "domain": "--"},
    "SD0024": {"primitive": "blank_field", "params": {"field": "--DTC"},
               "domain": "--", "guard": "--ENDTC != "},
    "SD0025": {"primitive": "invert_date_order",
               "params": {"start_field": "--DTC", "end_field": "--ENDTC"},
               "domain": "--"},
    "SD0026": {"primitive": "blank_field", "params": {"field": "--ORRESU"},
               "domain": "--", "guard": "--ORRES != "},
    "SD0027": {"primitive": "blank_field", "params": {"field": "--ORRES"},
               "domain": "--", "guard": "--ORRESU != "},
    "SD0028": {"primitive": "invert_date_order",
               "params": {"start_field": "--STNRHI", "end_field": "--STNRLO"},
               "domain": "--"},
    "SD0029": {"primitive": "blank_field", "params": {"field": "--STRESU"},
               "domain": "--", "guard": "--STRESC != "},
    "SD0030": {"primitive": "blank_field", "params": {"field": "--STRESC"},
               "domain": "--", "guard": "--STRESU != "},
    "SD0036": {"primitive": "blank_field", "params": {"field": "--STRESC"},
               "domain": "--", "guard": "--ORRES != "},
    "SD0045": {"primitive": "blank_field", "params": {"field": "--STRESC"},
               "domain": "--", "guard": "--RESCAT != "},
    "SD1043": {"primitive": "mismatch_pair",
               "params": {"field_a": "--TEST", "field_b": "--TESTCD"}, "domain": "--"},
    "SD1117": {"primitive": "duplicate_record",
               "params": {"key_fields": ["USUBJID", "--TESTCD", "--CAT", "--DTC"]},
               "domain": "--"},
    "SD1122": {"primitive": "blank_field", "params": {"field": "--STRESN"},
               "domain": "--", "guard": "--STRESC != "},
    "SD1123": {"primitive": "populate_forbidden",
               "params": {"field": "--ORRES", "value": "POPULATED"},
               "domain": "--", "guard": "--STAT == NOT DONE"},
    "SD1131": {"primitive": "blank_field", "params": {"field": "--STRESC"},
               "domain": "--", "guard": "--BLFL == Y"},
    "SD1212": {"primitive": "mismatch_pair",
               "params": {"field_a": "--STRESC", "field_b": "--STRESN"}, "domain": "--"},
    "SD1272": {"primitive": "set_invalid_value",
               "params": {"field": "--TESTCD", "value": "OTHER"},
               "domain": "--"},
    "SD1275": {"primitive": "set_invalid_value",
               "params": {"field": "--TESTCD", "value": "MULTIPLE"},
               "domain": "--"},
    "SD1320": {"primitive": "blank_field", "params": {"field": "--STRESC"},
               "domain": "--", "guard": "--STAT == "},
    "SD1330": {"primitive": "invert_date_order",
               "params": {"start_field": "--DY", "end_field": "--ENDY"},
               "domain": "--"},
    "SD1353": {"primitive": "mismatch_pair",
               "params": {"field_a": "--ORRES", "field_b": "--STRESC"},
               "domain": "--", "guard": "--STRESU == --ORRESU"},
    "SD1369": {"primitive": "blank_field", "params": {"field": "--STREFC"},
               "domain": "--", "guard": "--ORREF != "},
    "SD1370": {"primitive": "blank_field", "params": {"field": "--STREFN"},
               "domain": "--", "guard": "--STREFC != "},
    "SD1371": {"primitive": "blank_field", "params": {"field": "--ORRES"},
               "domain": "--", "guard": "--LOBXFL == Y"},
    "SD1372": {"primitive": "blank_field", "params": {"field": "--STRESC"},
               "domain": "--", "guard": "--LOBXFL == Y"},
    "SD1439": {"primitive": "duplicate_record",
               "params": {"key_fields": ["USUBJID", "--TESTCD", "--BLFL"]},
               "domain": "--", "guard": "--BLFL == Y"},
    "SD1445": {"primitive": "duplicate_record",
               "params": {"key_fields": ["USUBJID", "--TESTCD", "--LOBXFL"]},
               "domain": "--", "guard": "--LOBXFL == Y"},
    "SD1448": {"primitive": "mismatch_pair",
               "params": {"field_a": "--STRESC", "field_b": "--STRESN"},
               "domain": "--"},
    "SD2239": {"primitive": "mismatch_pair",
               "params": {"field_a": "--DTC", "field_b": "--TPT"}, "domain": "--"},

    # ========== general observations 1: timing/visit ==========
    "SD0002": {"primitive": "blank_field", "params": {"field": "USUBJID"},
               "domain": "--"},
    "SD0003": {"primitive": "set_invalid_value",
               "params": {"field": "--DTC", "value": "2024/01/99"},
               "domain": "--"},
    "SD0004": {"primitive": "set_invalid_value",
               "params": {"field": "DOMAIN", "value": "XX"},
               "domain": "--"},
    "SD0005": {"primitive": "duplicate_record",
               "params": {"key_fields": ["USUBJID", "--SEQ"]}, "domain": "--"},
    "SD0012": {"primitive": "invert_date_order",
               "params": {"start_field": "--STDY", "end_field": "--ENDY"},
               "domain": "--"},
    "SD0022": {"primitive": "blank_field", "params": {"field": "--STDTC"},
               "domain": "--", "guard": "--ENDTC != "},
    "SD0023": {"primitive": "blank_field", "params": {"field": "--STAT"},
               "domain": "--", "guard": "--REASND != "},
    "SD0031": {"primitive": "blank_field", "params": {"field": "--STDTC"},
               "domain": "--", "guard": "--ENDTC != "},
    "SD0032": {"primitive": "blank_field", "params": {"field": "--TPT"},
               "domain": "--", "guard": "--TPTNUM != "},
    "SD0033": {"primitive": "blank_field", "params": {"field": "--TPTNUM"},
               "domain": "--", "guard": "--TPT != "},
    "SD0034": {"primitive": "blank_field", "params": {"field": "--TPTREF"},
               "domain": "--", "guard": "--ELTM != "},
    "SD0049": {"primitive": "blank_field", "params": {"field": "--STTPT"},
               "domain": "--", "guard": "--STRTPT != "},
    "SD0050": {"primitive": "blank_field", "params": {"field": "--ENTPT"},
               "domain": "--", "guard": "--ENRTPT != "},
    "SD0051": {"primitive": "mismatch_pair",
               "params": {"field_a": "VISITNUM", "field_b": "VISIT"}, "domain": "--"},
    "SD0052": {"primitive": "mismatch_pair",
               "params": {"field_a": "VISIT", "field_b": "VISITNUM"}, "domain": "--"},
    "SD1084": {"primitive": "wrong_derived",
               "params": {"field": "--DY", "offset_range": [-5, 5]},
               "domain": "--"},
    "SD1088": {"primitive": "blank_field", "params": {"field": "--STDY"},
               "domain": "--", "guard": "--STDTC != "},
    "SD1089": {"primitive": "truncate_with_derived",
               "params": {"date_field": "--STDTC", "dy_field": "--STDY"},
               "domain": "--"},
    "SD1090": {"primitive": "wrong_derived",
               "params": {"field": "--STDY", "offset_range": [-5, 5]},
               "domain": "--"},
    "SD1092": {"primitive": "blank_field", "params": {"field": "--ENDY"},
               "domain": "--", "guard": "--ENDTC != "},
    "SD1093": {"primitive": "truncate_with_derived",
               "params": {"date_field": "--ENDTC", "dy_field": "--ENDY"},
               "domain": "--"},
    "SD1094": {"primitive": "wrong_derived",
               "params": {"field": "--ENDY", "offset_range": [-5, 5]},
               "domain": "--"},
    "SD1125": {"primitive": "mismatch_pair",
               "params": {"field_a": "--TPT", "field_b": "--ELTM"}, "domain": "--"},
    "SD1126": {"primitive": "mismatch_pair",
               "params": {"field_a": "--TPTNUM", "field_b": "--TPT"}, "domain": "--"},
    "SD1127": {"primitive": "mismatch_pair",
               "params": {"field_a": "--TPT", "field_b": "--TPTNUM"}, "domain": "--"},
    "SD1201": {"primitive": "duplicate_record",
               "params": {"key_fields": ["USUBJID", "--TERM", "--DECOD", "--CAT", "--STDTC"]},
               "domain": "--"},
    "SD1238": {"primitive": "blank_field", "params": {"field": "--TPTREF"},
               "domain": "--", "guard": "--RFTDTC != "},
    "SD1244": {"primitive": "blank_field", "params": {"field": "--TPT"},
               "domain": "--", "guard": "--TPTNUM != "},
    "SD1291": {"primitive": "blank_field", "params": {"field": "--ENRTPT"},
               "domain": "--", "guard": "--ENTPT != "},
    "SD1292": {"primitive": "blank_field", "params": {"field": "--STRTPT"},
               "domain": "--", "guard": "--STTPT != "},
    "SD1300": {"primitive": "set_invalid_value",
               "params": {"field": "DOMAIN", "value": "ZZ"},
               "domain": "--"},
    "SD1331": {"primitive": "invert_date_order",
               "params": {"start_field": "--DTC", "end_field": "--STDTC"},
               "domain": "--"},
    "SD1339": {"primitive": "blank_field", "params": {"field": "EPOCH"},
               "domain": "--", "guard": "--DTC != "},
    "SD2238": {"primitive": "mismatch_pair",
               "params": {"field_a": "--STDTC", "field_b": "--STTPT"}, "domain": "--"},

    # ========== general observations 2: structural/variable ==========
    "SD0055": {"primitive": "set_invalid_value",
               "params": {"field": "USUBJID", "value": "123"},
               "domain": "--"},
    "SD0056": {"primitive": "drop_column",
               "params": {"column": "USUBJID"}, "domain": "--"},
    "SD0057": {"primitive": "drop_column",
               "params": {"column": "--DTC"}, "domain": "--"},
    "SD0063": {"primitive": "set_invalid_value",
               "params": {"field": "LABEL", "value": "WRONG LABEL"},
               "domain": "--"},
    "SD0063A": {"primitive": "set_invalid_value",
                "params": {"field": "LABEL", "value": "WRONG LABEL 2"},
                "domain": "--"},
    "SD0064": {"primitive": "cross_domain_mismatch",
               "params": {"source": "--", "source_field": "USUBJID",
                          "target": "DM", "target_field": "USUBJID",
                          "mismatch_type": "not_in_set"},
               "domain": "--"},
    "SD0065": {"primitive": "cross_domain_mismatch",
               "params": {"source": "--", "source_field": "VISITNUM",
                          "target": "SV", "target_field": "VISITNUM",
                          "mismatch_type": "not_in_set"},
               "domain": "--"},
    "SD1005": {"primitive": "set_invalid_value",
               "params": {"field": "STUDYID", "value": "WRONG_STUDY_999"},
               "domain": "--"},
    "SD1011": {"primitive": "set_invalid_value",
               "params": {"field": "STUDYID", "value": "INVALID DATE 9999/99/99"},
               "domain": "--"},
    "SD1021": {"primitive": "set_invalid_value",
               "params": {"field": "--DUR", "value": "NOT_ISO8601"},
               "domain": "--"},
    "SD1029": {"primitive": "set_invalid_value",
               "params": {"field": "--TEST", "value": "Tëst Wïth Nön-ÄSCII"},
               "domain": "--"},
    "SD1078": {"primitive": "blank_field", "params": {"field": "--ORRES"},
               "domain": "--"},
    "SD1082": {"primitive": "set_invalid_value",
               "params": {"field": "--TERM", "value": "A" * 210},
               "domain": "--"},
    "SD1095": {"primitive": "set_invalid_value",
               "params": {"field": "DOMAIN", "value": "AA1"},
               "domain": "--"},
    "SD1098": {"primitive": "blank_field", "params": {"field": "--CAT"},
               "domain": "--", "guard": "--SCAT != "},
    "SD1116": {"primitive": "set_invalid_value",
               "params": {"field": "--ORRESU", "value": "INCONSISTENT_UNIT_XYZ"},
               "domain": "--"},
    "SD1118": {"primitive": "blank_field", "params": {"field": "--STDTC"},
               "domain": "DS"},
    "SD1124": {"primitive": "blank_field", "params": {"field": "--REASND"},
               "domain": "--", "guard": "--STAT == NOT DONE"},
    "SD1128": {"primitive": "set_invalid_value",
               "params": {"field": "RELTYPE", "value": "INVALID"},
               "domain": "RELREC"},
    "SD1130": {"primitive": "mismatch_pair",
               "params": {"field_a": "QNAM", "field_b": "QLABEL"}, "domain": "SUPPQUAL"},
    "SD1147": {"primitive": "drop_column",
               "params": {"column": "--PRESP"}, "domain": "--"},
    "SD1234": {"primitive": "blank_field", "params": {"field": "DIPARMCD"},
               "domain": "DI", "guard": "DIPARMCD != DEVTYPE"},
    "SD1235": {"primitive": "blank_field", "params": {"field": "SPDEVID"},
               "domain": "DU"},
    "SD1236": {"primitive": "duplicate_record",
               "params": {"key_fields": ["USUBJID", "--SEQ"]}, "domain": "--"},
    "SD1237": {"primitive": "duplicate_record",
               "params": {"key_fields": ["USUBJID", "SPDEVID", "--SEQ"]}, "domain": "DO"},
    "SD1241": {"primitive": "blank_field", "params": {"field": "--BODSYS"},
               "domain": "--", "guard": "--BDSYCD != "},
    "SD1242": {"primitive": "mismatch_pair",
               "params": {"field_a": "--BDSYCD", "field_b": "--BODSYS"}, "domain": "--"},
    "SD1243": {"primitive": "mismatch_pair",
               "params": {"field_a": "--BODSYS", "field_b": "--BDSYCD"}, "domain": "--"},
    "SD1247": {"primitive": "blank_field", "params": {"field": "ECDOSE"},
               "domain": "EC", "guard": "ECOCCUR != N"},
    "SD1248": {"primitive": "set_invalid_value",
               "params": {"field": "ECDOSE", "value": "5"},
               "domain": "EC", "guard": "ECOCCUR == N"},
    "SD1249": {"primitive": "set_invalid_value",
               "params": {"field": "EXDOSE", "value": "10"},
               "domain": "EX", "guard": "EXTRT == PLACEBO"},
    "SD1251": {"primitive": "populate_forbidden",
               "params": {"field": "--VAMTU", "value": "mg"},
               "domain": "--", "guard": "--TRTV == "},
    "SD1264": {"primitive": "set_invalid_value",
               "params": {"field": "IDVAR", "value": "--SEQ"},
               "domain": "RELREC"},
    "SD1265": {"primitive": "blank_field", "params": {"field": "QEVAL"},
               "domain": "SUPPQUAL", "guard": "QORIG == ASSIGNED"},
    "SD1279": {"primitive": "blank_field", "params": {"field": "ECDOSTXT"},
               "domain": "EC", "guard": "ECDOSE == "},
    "SD1287": {"primitive": "mismatch_pair",
               "params": {"field_a": "--PTCD", "field_b": "--DECOD"}, "domain": "--"},
    "SD1288": {"primitive": "mismatch_pair",
               "params": {"field_a": "--DECOD", "field_b": "--PTCD"}, "domain": "--"},
    "SD1289": {"primitive": "blank_field", "params": {"field": "--DECOD"},
               "domain": "--", "guard": "--PTCD != "},
    "SD1298": {"primitive": "set_invalid_value",
               "params": {"field": "LBTOXGR", "value": "SEVERE"},
               "domain": "LB"},
    "SD1326": {"primitive": "populate_forbidden",
               "params": {"field": "RDEVID", "value": "DEV001"},
               "domain": "--", "guard": "RSUBJID != "},
    "SD1327": {"primitive": "mismatch_pair",
               "params": {"field_a": "POOLID", "field_b": "RSUBJID"}, "domain": "RELREC"},
    "SD1328": {"primitive": "mismatch_pair",
               "params": {"field_a": "USUBJID", "field_b": "RSUBJID"}, "domain": "RELREC"},
    "SD1352": {"primitive": "duplicate_record",
               "params": {"key_fields": ["USUBJID", "--TRT", "--STDTC", "--ENDTC"]},
               "domain": "--"},
    "SD1365": {"primitive": "set_invalid_value",
               "params": {"field": "QNAM", "value": "ADSLFL01"},
               "domain": "SUPPQUAL"},
    "SD1380": {"primitive": "blank_field", "params": {"field": "USUBJID"},
               "domain": "--"},
    "SD1440": {"primitive": "mismatch_pair",
               "params": {"field_a": "--TERM", "field_b": "--DECOD"}, "domain": "--"},
    "SD1441": {"primitive": "mismatch_pair",
               "params": {"field_a": "--TERM", "field_b": "--HLT"}, "domain": "--"},
    "SD1442": {"primitive": "mismatch_pair",
               "params": {"field_a": "--TERM", "field_b": "--HLGT"}, "domain": "--"},
    "SD1443": {"primitive": "mismatch_pair",
               "params": {"field_a": "--TERM", "field_b": "--BODSYS"}, "domain": "--"},
    "SD1444": {"primitive": "mismatch_pair",
               "params": {"field_a": "--TERM", "field_b": "--SOC"}, "domain": "--"},
    "SD1449": {"primitive": "blank_field", "params": {"field": "AEDECOD"},
               "domain": "AE"},
    "SD1452": {"primitive": "set_invalid_value",
               "params": {"field": "--VAMT", "value": "-10"},
               "domain": "--"},
    "SD1453": {"primitive": "duplicate_record",
               "params": {"key_fields": ["SPDEVID", "--SEQ"]}, "domain": "DI"},
    "SD2006": {"primitive": "set_invalid_value",
               "params": {"field": "QNAM", "value": "AELLT"},
               "domain": "SUPPQUAL"},
    "SD2024": {"primitive": "populate_forbidden",
               "params": {"field": "POOLID", "value": "POOL001"},
               "domain": "--", "guard": "USUBJID != "},

    # ========== interventions/events ==========
    "SD0006": {"primitive": "cross_domain_orphan",
               "params": {"source": "--", "target": "--", "key": "USUBJID"},
               "guard": "BLFL == Y"},
    "SD0009": {"primitive": "blank_field", "params": {"field": "AESER"},
               "domain": "AE", "guard": "AESER == Y"},
    "SD0014": {"primitive": "set_invalid_value",
               "params": {"field": "--DOSE", "value": "-5"},
               "domain": "--"},
    "SD0015": {"primitive": "set_invalid_value",
               "params": {"field": "--DUR", "value": "-P1D"},
               "domain": "--"},
    "SD0035": {"primitive": "blank_field", "params": {"field": "--DOSU"},
               "domain": "--", "guard": "--DOSE != "},
    "SD0041": {"primitive": "populate_forbidden",
               "params": {"field": "--OCCUR", "value": "Y"},
               "domain": "--", "guard": "--PRESP == "},
    "SD0042": {"primitive": "set_invalid_value",
               "params": {"field": "--STAT", "value": "COMPLETED"},
               "domain": "--", "guard": "--PRESP == Y"},
    "SD0043": {"primitive": "blank_field", "params": {"field": "--TRTV"},
               "domain": "--", "guard": "--VAMT != "},
    "SD0044": {"primitive": "blank_field", "params": {"field": "--VAMTU"},
               "domain": "--", "guard": "--VAMT != "},
    "SD0046": {"primitive": "mismatch_pair",
               "params": {"field_a": "QNAM", "field_b": "QLABEL"}, "domain": "SUPPQUAL"},
    "SD0079": {"primitive": "populate_forbidden",
               "params": {"field": "EPOCH", "value": "SCREENING"},
               "domain": "EX", "guard": "ARMCD == SCRNFAIL"},
    "SD0080": {"primitive": "cross_domain_mismatch",
               "params": {"source": "AE", "source_field": "AESTDTC",
                          "target": "DS", "target_field": "DSSTDTC",
                          "mismatch_type": "date_after"},
               "domain": "AE"},
    "SD0082": {"primitive": "cross_domain_mismatch",
               "params": {"source": "EX", "source_field": "EXENDTC",
                          "target": "DS", "target_field": "DSSTDTC",
                          "mismatch_type": "date_after"},
               "domain": "EX"},
    "SD0085": {"primitive": "mismatch_pair",
               "params": {"field_a": "IEORRES", "field_b": "IESTRESC"}, "domain": "IE"},
    "SD0086": {"primitive": "duplicate_record",
               "params": {"key_fields": ["QNAM", "QLABEL"]}, "domain": "SUPPQUAL"},
    "SD0090": {"primitive": "set_invalid_value",
               "params": {"field": "AESDTH", "value": "N"},
               "domain": "AE", "guard": "AEOUT == FATAL"},
    "SD0091": {"primitive": "set_invalid_value",
               "params": {"field": "AEOUT", "value": "NOT RECOVERED/NOT RESOLVED"},
               "domain": "AE", "guard": "AESDTH == Y"},
    "SD0092": {"primitive": "blank_field", "params": {"field": "SEUPDES"},
               "domain": "SE", "guard": "ETCD == UNPLAN"},
    "SD1030": {"primitive": "populate_forbidden",
               "params": {"field": "--STRF", "value": "BEFORE"},
               "domain": "--", "guard": "RFSTDTC == "},
    "SD1031": {"primitive": "populate_forbidden",
               "params": {"field": "--ENRF", "value": "AFTER"},
               "domain": "--", "guard": "RFENDTC == "},
    "SD1035": {"primitive": "blank_field", "params": {"field": "DSCAT"},
               "domain": "DS"},
    "SD1036": {"primitive": "blank_field", "params": {"field": "--TOXGR"},
               "domain": "--", "guard": "--TOX != "},
    "SD1037": {"primitive": "blank_field", "params": {"field": "--TOX"},
               "domain": "--", "guard": "--TOXGR != "},
    "SD1039": {"primitive": "set_invalid_value",
               "params": {"field": "--CAT", "value": "DOMAIN_NAME_COPY"},
               "domain": "--"},
    "SD1040": {"primitive": "set_invalid_value",
               "params": {"field": "--SCAT", "value": "DOMAIN_NAME_COPY"},
               "domain": "--"},
    "SD1041": {"primitive": "mismatch_pair",
               "params": {"field_a": "--CAT", "field_b": "--SCAT"}, "domain": "--"},
    "SD1042": {"primitive": "populate_forbidden",
               "params": {"field": "--STRF", "value": "BEFORE"},
               "domain": "--", "guard": "--OCCUR == N"},
    "SD1045": {"primitive": "mismatch_pair",
               "params": {"field_a": "IECAT", "field_b": "IEORRES"}, "domain": "IE"},
    "SD1046": {"primitive": "mismatch_pair",
               "params": {"field_a": "IECAT", "field_b": "IEORRES"}, "domain": "IE"},
    "SD1047": {"primitive": "populate_forbidden",
               "params": {"field": "--DOSTXT", "value": "ABOUT 10 MG"},
               "domain": "--", "guard": "--DOSE != "},
    "SD1062": {"primitive": "set_invalid_value",
               "params": {"field": "AESER", "value": "N"},
               "domain": "AE", "guard": "AESOD == Y"},
    "SD1096": {"primitive": "set_invalid_value",
               "params": {"field": "--TERM", "value": "A" * 210},
               "domain": "--"},
    "SD1097": {"primitive": "cross_domain_orphan",
               "params": {"source": "AE", "target": "SUPPAE", "key": "USUBJID"}},
    "SD1105": {"primitive": "populate_forbidden",
               "params": {"field": "EPOCH", "value": "TREATMENT"},
               "domain": "DS", "guard": "DSCAT == PROTOCOL MILESTONE"},
    "SD1120": {"primitive": "populate_forbidden",
               "params": {"field": "QNAM", "value": "COMMENT01"},
               "domain": "SUPPQUAL"},
    "SD1132": {"primitive": "set_invalid_value",
               "params": {"field": "AESER", "value": "N"},
               "domain": "AE"},
    "SD1135": {"primitive": "set_invalid_value",
               "params": {"field": "--STDY", "value": "-5"},
               "domain": "--"},
    "SD1143": {"primitive": "cross_domain_orphan",
               "params": {"source": "AE", "target": "SUPPAE", "key": "USUBJID"},
               "guard": "AESMIE != "},
    "SD1144": {"primitive": "cross_domain_mismatch",
               "params": {"source": "MH", "source_field": "MHSTDTC",
                          "target": "DM", "target_field": "RFSTDTC",
                          "mismatch_type": "date_after"},
               "domain": "MH"},
    "SD1150": {"primitive": "mismatch_pair",
               "params": {"field_a": "IETESTCD", "field_b": "IETEST"}, "domain": "TI"},
    "SD1151": {"primitive": "mismatch_pair",
               "params": {"field_a": "IETEST", "field_b": "IETESTCD"}, "domain": "TI"},
    "SD1205": {"primitive": "cross_domain_mismatch",
               "params": {"source": "EX", "source_field": "EXSTDTC",
                          "target": "DM", "target_field": "RFXSTDTC",
                          "mismatch_type": "date_before"},
               "domain": "EX"},
    "SD1206": {"primitive": "cross_domain_mismatch",
               "params": {"source": "EX", "source_field": "EXSTDTC",
                          "target": "DM", "target_field": "RFXENDTC",
                          "mismatch_type": "date_after"},
               "domain": "EX"},
    "SD1207": {"primitive": "cross_domain_mismatch",
               "params": {"source": "EX", "source_field": "EXENDTC",
                          "target": "DM", "target_field": "RFXENDTC",
                          "mismatch_type": "date_after"},
               "domain": "EX"},
    "SD1262": {"primitive": "cross_domain_mismatch",
               "params": {"source": "SS", "source_field": "SSDTC",
                          "target": "DS", "target_field": "DSSTDTC",
                          "mismatch_type": "date_before"},
               "domain": "SS", "guard": "SSSTRESC == DEAD"},
    "SD1273": {"primitive": "set_invalid_value",
               "params": {"field": "--TRT", "value": "OTHER"},
               "domain": "--"},
    "SD1274": {"primitive": "set_invalid_value",
               "params": {"field": "--TERM", "value": "OTHER"},
               "domain": "--"},
    "SD1276": {"primitive": "set_invalid_value",
               "params": {"field": "--TRT", "value": "MULTIPLE"},
               "domain": "--"},
    "SD1277": {"primitive": "set_invalid_value",
               "params": {"field": "--TERM", "value": "MULTIPLE"},
               "domain": "--"},
    "SD1290": {"primitive": "duplicate_record",
               "params": {"key_fields": ["USUBJID", "EPOCH", "DSTERM"]}, "domain": "DS"},
    "SD1313": {"primitive": "blank_field", "params": {"field": "EPOCH"},
               "domain": "DS", "guard": "DSCAT == DISPOSITION EVENT"},
    "SD1314": {"primitive": "mismatch_pair",
               "params": {"field_a": "DSTERM", "field_b": "DSDECOD"},
               "domain": "DS", "guard": "DSTERM == COMPLETED"},
    "SD1315": {"primitive": "mismatch_pair",
               "params": {"field_a": "DSTERM", "field_b": "DSDECOD"},
               "domain": "DS", "guard": "DSCAT == PROTOCOL MILESTONE"},
    "SD1318": {"primitive": "cross_domain_orphan",
               "params": {"source": "DS", "target": "DV", "key": "USUBJID"},
               "guard": "DSDECOD == DEATH"},
    "SD1319": {"primitive": "cross_domain_mismatch",
               "params": {"source": "--", "source_field": "--STDTC",
                          "target": "DM", "target_field": "RFICDTC",
                          "mismatch_type": "date_before"},
               "domain": "--"},
    "SD1321": {"primitive": "cross_domain_orphan",
               "params": {"source": "AE", "target": "SUPPAE", "key": "USUBJID"}},
    "SD1332": {"primitive": "populate_forbidden",
               "params": {"field": "AEENDTC", "value": "2024-06-01"},
               "domain": "AE", "guard": "AEOUT == NOT RECOVERED/NOT RESOLVED"},
    "SD1333": {"primitive": "blank_field", "params": {"field": "AEENDTC"},
               "domain": "AE", "guard": "AEOUT == RECOVERED/RESOLVED"},
    "SD1340": {"primitive": "populate_forbidden",
               "params": {"field": "EPOCH", "value": "TREATMENT"},
               "domain": "EX", "guard": "ACTARMCD == NOTTRT"},
    "SD1346": {"primitive": "cross_domain_mismatch",
               "params": {"source": "EX", "source_field": "EXSTDTC",
                          "target": "DS", "target_field": "DSSTDTC",
                          "mismatch_type": "date_after"},
               "domain": "EX"},
    "SD1373": {"primitive": "populate_forbidden",
               "params": {"field": "RFSTDTC", "value": "2024-01-01"},
               "domain": "DM", "guard": "ARMNRS != "},
    "SD1375": {"primitive": "populate_forbidden",
               "params": {"field": "RFENDTC", "value": "2024-12-31"},
               "domain": "DM", "guard": "ACTARMCD in (SCRNFAIL,NOTASSGN,NOTTRT,)"},
    "SD1446": {"primitive": "cross_domain_mismatch",
               "params": {"source": "EX", "source_field": "EXSTDTC",
                          "target": "DS", "target_field": "DSSTDTC",
                          "mismatch_type": "date_after"},
               "domain": "EX"},

    # ========== trial design / special-purpose ==========
    "SD0067": {"primitive": "cross_domain_mismatch",
               "params": {"source": "SE", "source_field": "ETCD",
                          "target": "TE", "target_field": "ETCD",
                          "mismatch_type": "not_in_set"},
               "domain": "SE"},
    "SD0068": {"primitive": "cross_domain_mismatch",
               "params": {"source": "IE", "source_field": "IETESTCD",
                          "target": "TI", "target_field": "IETESTCD",
                          "mismatch_type": "not_in_set"},
               "domain": "IE"},
    "SD0072": {"primitive": "set_invalid_value",
               "params": {"field": "RDOMAIN", "value": "ZZ"},
               "domain": "RELREC"},
    "SD0075": {"primitive": "set_invalid_value",
               "params": {"field": "IDVAR", "value": "NOVAR"},
               "domain": "RELREC"},
    "SD0077": {"primitive": "cross_domain_mismatch",
               "params": {"source": "RELREC", "source_field": "IDVARVAL",
                          "target": "--", "target_field": "--SEQ",
                          "mismatch_type": "not_in_set"},
               "domain": "RELREC"},
    "SD0089": {"primitive": "blank_field", "params": {"field": "TEENRL"},
               "domain": "TE"},
    "SD1009": {"primitive": "set_invalid_value",
               "params": {"field": "ETCD", "value": "INVALID_ETCD_XYZ"},
               "domain": "SE"},
    "SD1010": {"primitive": "populate_forbidden",
               "params": {"field": "ELEMENT", "value": "SOME ELEMENT"},
               "domain": "SE", "guard": "ETCD == UNPLAN"},
    "SD1012": {"primitive": "cross_domain_mismatch",
               "params": {"source": "SE", "source_field": "ETCD",
                          "target": "TE", "target_field": "ETCD",
                          "mismatch_type": "not_equal"},
               "domain": "SE"},
    "SD1013": {"primitive": "populate_forbidden",
               "params": {"field": "TAETORD", "value": "1"},
               "domain": "SE", "guard": "ETCD == UNPLAN"},
    "SD1014": {"primitive": "cross_domain_mismatch",
               "params": {"source": "--", "source_field": "TAETORD",
                          "target": "TA", "target_field": "TAETORD",
                          "mismatch_type": "not_in_set"},
               "domain": "--"},
    "SD1015": {"primitive": "cross_domain_mismatch",
               "params": {"source": "--", "source_field": "EPOCH",
                          "target": "TA", "target_field": "EPOCH",
                          "mismatch_type": "not_in_set"},
               "domain": "--"},
    "SD1016": {"primitive": "cross_domain_mismatch",
               "params": {"source": "IE", "source_field": "IETESTCD",
                          "target": "TI", "target_field": "IETESTCD",
                          "mismatch_type": "not_equal"},
               "domain": "IE"},
    "SD1017": {"primitive": "cross_domain_mismatch",
               "params": {"source": "SV", "source_field": "VISITNUM",
                          "target": "TV", "target_field": "VISITNUM",
                          "mismatch_type": "not_in_set"},
               "domain": "SV"},
    "SD1018": {"primitive": "cross_domain_mismatch",
               "params": {"source": "SV", "source_field": "VISITNUM,VISIT,VISITDY",
                          "target": "TV", "target_field": "VISITNUM,VISIT,VISITDY",
                          "mismatch_type": "combo_not_in_set"},
               "domain": "SV"},
    "SD1019": {"primitive": "populate_forbidden",
               "params": {"field": "VISITDY", "value": "1"},
               "domain": "SV", "guard": "SVUPDES != "},
    "SD1022": {"primitive": "set_invalid_value",
               "params": {"field": "QNAM", "value": "invalid qnam 99!"},
               "domain": "SUPPQUAL"},
    "SD1023": {"primitive": "cross_domain_mismatch",
               "params": {"source": "--", "source_field": "VISITNUM",
                          "target": "TV", "target_field": "VISITNUM",
                          "mismatch_type": "not_in_set"},
               "domain": "--"},
    "SD1026": {"primitive": "set_invalid_value",
               "params": {"field": "RELTYPE", "value": "INVALID"},
               "domain": "RELREC"},
    "SD1027": {"primitive": "duplicate_record",
               "params": {"key_fields": ["ETCD", "ELEMENT"]}, "domain": "TE"},
    "SD1050": {"primitive": "duplicate_record",
               "params": {"key_fields": ["ELEMENT", "ETCD"]}, "domain": "TE"},
    "SD1051": {"primitive": "set_invalid_value",
               "params": {"field": "IDVAR", "value": "FAKEVARIABLE"},
               "domain": "SUPPQUAL"},
    "SD1052": {"primitive": "duplicate_record",
               "params": {"key_fields": ["ARMCD", "TAETORD"]}, "domain": "TA"},
    "SD1053": {"primitive": "set_invalid_value",
               "params": {"field": "ARMCD", "value": "NOTINPROT"},
               "domain": "TA"},
    "SD1060": {"primitive": "duplicate_record",
               "params": {"key_fields": ["USUBJID", "VISITNUM"]}, "domain": "SV"},
    "SD1064": {"primitive": "duplicate_record",
               "params": {"key_fields": ["ETCD"]}, "domain": "TE"},
    "SD1066": {"primitive": "populate_forbidden",
               "params": {"field": "IDVARVAL", "value": "1"},
               "domain": "RELREC", "guard": "RELTYPE != "},
    "SD1067": {"primitive": "populate_forbidden",
               "params": {"field": "USUBJID", "value": "SUBJ001"},
               "domain": "RELREC", "guard": "RELTYPE != "},
    "SD1068": {"primitive": "duplicate_record",
               "params": {"key_fields": ["ELEMENT"]}, "domain": "TE"},
    "SD1069": {"primitive": "mismatch_pair",
               "params": {"field_a": "--PARMCD", "field_b": "--PARM"}, "domain": "TS"},
    "SD1070": {"primitive": "mismatch_pair",
               "params": {"field_a": "--PARM", "field_b": "--PARMCD"}, "domain": "TS"},
    "SD1072": {"primitive": "blank_field", "params": {"field": "IDVAR"},
               "domain": "RELREC", "guard": "RDOMAIN != "},
    "SD1201": {"primitive": "duplicate_record",
               "params": {"key_fields": ["USUBJID", "--TERM", "--DECOD", "--STDTC"]},
               "domain": "--"},
    "SD1233": {"primitive": "cross_domain_mismatch",
               "params": {"source": "--", "source_field": "SPDEVID",
                          "target": "DI", "target_field": "SPDEVID",
                          "mismatch_type": "not_in_set"},
               "domain": "--"},
    "SD1266": {"primitive": "blank_field", "params": {"field": "SEUPDES"},
               "domain": "SE", "guard": "ETCD == UNPLAN"},
    "SD1267": {"primitive": "set_invalid_value",
               "params": {"field": "TAETORD", "value": "0"},
               "domain": "TA"},
    "SD1271": {"primitive": "duplicate_record",
               "params": {"key_fields": ["ETCD", "ELEMENT", "TESTRL", "TEENRL", "TEDUR"]},
               "domain": "TE"},
    "SD1278": {"primitive": "mismatch_pair",
               "params": {"field_a": "TSVAL", "field_b": "TSVALCD"}, "domain": "TS"},
    "SD1286": {"primitive": "duplicate_record",
               "params": {"key_fields": ["IETESTCD", "TIVERS"]}, "domain": "TI"},
    "SD1354": {"primitive": "cross_domain_mismatch",
               "params": {"source": "TA", "source_field": "ARMCD",
                          "target": "DM", "target_field": "ARMCD",
                          "mismatch_type": "not_in_set"},
               "domain": "TA"},
    "SD1378": {"primitive": "cross_domain_mismatch",
               "params": {"source": "TE", "source_field": "ETCD",
                          "target": "TA", "target_field": "ETCD",
                          "mismatch_type": "not_in_set"},
               "domain": "TE"},
    "SD1379": {"primitive": "cross_domain_mismatch",
               "params": {"source": "TE", "source_field": "ETCD",
                          "target": "SE", "target_field": "ETCD",
                          "mismatch_type": "not_in_set"},
               "domain": "TE"},

    # ========== dataset-level (drop_domain, 12 rules) ==========
    "SD1020": {"primitive": "drop_domain", "params": {"domain": "DM"}},
    "SD1111": {"primitive": "drop_domain", "params": {"domain": "TA"}},
    "SD1109": {"primitive": "drop_domain", "params": {"domain": "TE"}},
    "SD1106": {"primitive": "drop_domain", "params": {"domain": "AE"}},
    "SD1110": {"primitive": "drop_domain", "params": {"domain": "DS"}},
    "SD1107": {"primitive": "drop_domain", "params": {"domain": "LB"}},
    "SD1108": {"primitive": "drop_domain", "params": {"domain": "VS"}},
    "SD1112": {"primitive": "drop_domain", "params": {"domain": "TA"}},
    "SD1113": {"primitive": "drop_domain", "params": {"domain": "TE"}},
    "SD1115": {"primitive": "drop_domain", "params": {"domain": "TS"}},
    "SD1270": {"primitive": "drop_domain", "params": {"domain": "PC"}},
    "SD1061": {"primitive": "drop_domain", "params": {"domain": "MB"}},

    # ========== variable-level (drop_column, add_column, reorder) ==========
    "SD1083": {"primitive": "drop_column", "params": {"column": "--DY"}, "domain": "--"},
    "SD1129": {"primitive": "drop_column", "params": {"column": "AGE"}, "domain": "DM"},
    "SD2270": {"primitive": "drop_column", "params": {"column": "--DTC"}, "domain": "--",
               "guard": "--DY exists"},
    "SD2271": {"primitive": "drop_column", "params": {"column": "--STDTC"}, "domain": "--",
               "guard": "--STDY exists"},
    "SD2272": {"primitive": "drop_column", "params": {"column": "--ENDTC"}, "domain": "--",
               "guard": "--ENDY exists"},
    "SD1087": {"primitive": "drop_column", "params": {"column": "--STDY"}, "domain": "--"},
    "SD1091": {"primitive": "drop_column", "params": {"column": "--ENDY"}, "domain": "--"},
    "SD1099": {"primitive": "drop_column", "params": {"column": "--CAT"}, "domain": "--",
               "guard": "--SCAT exists"},
    "SD1101": {"primitive": "drop_column", "params": {"column": "--ENTPT"}, "domain": "--"},
    "SD1102": {"primitive": "drop_column", "params": {"column": "--ENRTPT"}, "domain": "--"},
    "SD1103": {"primitive": "drop_column", "params": {"column": "--STTPT"}, "domain": "--"},
    "SD1104": {"primitive": "drop_column", "params": {"column": "--STRTPT"}, "domain": "--"},
    "SD1044": {"primitive": "drop_column", "params": {"column": "--BLFL"}, "domain": "--"},
    "SD1245": {"primitive": "drop_column", "params": {"column": "--TPTREF"}, "domain": "--",
               "guard": "--RFTDTC exists"},
    "SD1246": {"primitive": "drop_column", "params": {"column": "--TPTREF"}, "domain": "--",
               "guard": "--ELTM exists"},
    "SD1250": {"primitive": "drop_column", "params": {"column": "--TPTNUM"}, "domain": "--",
               "guard": "--TPT exists"},
    "SD1280": {"primitive": "drop_column", "params": {"column": "--TOX"}, "domain": "--",
               "guard": "--TOXGR exists"},
    "SD1282": {"primitive": "drop_column", "params": {"column": "--TPTREF"}, "domain": "--"},
    "SD1283": {"primitive": "drop_column", "params": {"column": "--LOC"}, "domain": "--",
               "guard": "--LAT exists"},
    "SD1284": {"primitive": "drop_column", "params": {"column": "--LOC"}, "domain": "--",
               "guard": "--PORTOT exists"},
    "SD1285": {"primitive": "drop_column", "params": {"column": "--LOC"}, "domain": "--",
               "guard": "--DIR exists"},
    "SD1293": {"primitive": "drop_column", "params": {"column": "--PRESP"}, "domain": "--",
               "guard": "--REASND exists"},
    "SD1294": {"primitive": "drop_column", "params": {"column": "--PRESP"}, "domain": "--",
               "guard": "--STAT exists"},
    "SD1299": {"primitive": "drop_column", "params": {"column": "--DTC"}, "domain": "--"},
    "SD1357": {"primitive": "drop_column", "params": {"column": "MIDS"}, "domain": "--",
               "guard": "MIDSDTC exists"},
    "SD1450": {"primitive": "drop_column", "params": {"column": "--ENINT"}, "domain": "--",
               "guard": "--STINT exists"},
    "SD1451": {"primitive": "drop_column", "params": {"column": "--STINT"}, "domain": "--",
               "guard": "--ENINT exists"},
    "SD1077": {"primitive": "drop_column", "params": {"column": "USUBJID"}, "domain": "--"},
    "SD0058": {"primitive": "add_column", "params": {"column_name": "CUSTOMVAR", "fill_value": ""}, "domain": "--"},
    "SD1073": {"primitive": "add_column", "params": {"column_name": "AEACNDEV", "fill_value": ""}, "domain": "--"},
    "SD1074": {"primitive": "add_column", "params": {"column_name": "GRPID", "fill_value": "1"}, "domain": "--"},
    "SD1075": {"primitive": "add_column", "params": {"column_name": "AEREF", "fill_value": ""}, "domain": "AE"},
    "SD1076": {"primitive": "add_column", "params": {"column_name": "AEMODIFY", "fill_value": ""}, "domain": "AE"},
    "SD1079": {"primitive": "reorder_columns", "params": {"col_a": "STUDYID", "col_b": "DOMAIN"}, "domain": "--"},

    # ========== TS rules: delete_row (50 rules) ==========
    "SD2201": {"primitive": "delete_row", "params": {"filter_field": "TSPARMCD", "filter_value": "ADDON"}, "domain": "TS"},
    "SD2202": {"primitive": "delete_row", "params": {"filter_field": "TSPARMCD", "filter_value": "AGEMAX"}, "domain": "TS"},
    "SD2203": {"primitive": "delete_row", "params": {"filter_field": "TSPARMCD", "filter_value": "AGEMIN"}, "domain": "TS"},
    "SD2204": {"primitive": "delete_row", "params": {"filter_field": "TSPARMCD", "filter_value": "LENGTH"}, "domain": "TS"},
    "SD2205": {"primitive": "delete_row", "params": {"filter_field": "TSPARMCD", "filter_value": "PLANSUB"}, "domain": "TS"},
    "SD2206": {"primitive": "delete_row", "params": {"filter_field": "TSPARMCD", "filter_value": "RANDOM"}, "domain": "TS"},
    "SD2207": {"primitive": "delete_row", "params": {"filter_field": "TSPARMCD", "filter_value": "SEXPOP"}, "domain": "TS"},
    "SD2208": {"primitive": "delete_row", "params": {"filter_field": "TSPARMCD", "filter_value": "STOPRULE"}, "domain": "TS"},
    "SD2209": {"primitive": "delete_row", "params": {"filter_field": "TSPARMCD", "filter_value": "TBLIND"}, "domain": "TS"},
    "SD2210": {"primitive": "delete_row", "params": {"filter_field": "TSPARMCD", "filter_value": "TCNTRL"}, "domain": "TS"},
    "SD2211": {"primitive": "delete_row", "params": {"filter_field": "TSPARMCD", "filter_value": "TDIGRP"}, "domain": "TS"},
    "SD2212": {"primitive": "delete_row", "params": {"filter_field": "TSPARMCD", "filter_value": "TINDTP"}, "domain": "TS"},
    "SD2213": {"primitive": "delete_row", "params": {"filter_field": "TSPARMCD", "filter_value": "TITLE"}, "domain": "TS"},
    "SD2214": {"primitive": "delete_row", "params": {"filter_field": "TSPARMCD", "filter_value": "TPHASE"}, "domain": "TS"},
    "SD2215": {"primitive": "delete_row", "params": {"filter_field": "TSPARMCD", "filter_value": "TTYPE"}, "domain": "TS"},
    "SD2216": {"primitive": "delete_row", "params": {"filter_field": "TSPARMCD", "filter_value": "CURTRT"}, "domain": "TS"},
    "SD2217": {"primitive": "delete_row", "params": {"filter_field": "TSPARMCD", "filter_value": "OBJPRIM"}, "domain": "TS"},
    "SD2218": {"primitive": "delete_row", "params": {"filter_field": "TSPARMCD", "filter_value": "SPONSOR"}, "domain": "TS"},
    "SD2219": {"primitive": "delete_row", "params": {"filter_field": "TSPARMCD", "filter_value": "TRT"}, "domain": "TS"},
    "SD2221": {"primitive": "delete_row", "params": {"filter_field": "TSPARMCD", "filter_value": "REGID"}, "domain": "TS"},
    "SD2222": {"primitive": "delete_row", "params": {"filter_field": "TSPARMCD", "filter_value": "OUTMSPRI"}, "domain": "TS"},
    "SD2223": {"primitive": "delete_row", "params": {"filter_field": "TSPARMCD", "filter_value": "PCLAS"}, "domain": "TS"},
    "SD2224": {"primitive": "delete_row", "params": {"filter_field": "TSPARMCD", "filter_value": "FCNTRY"}, "domain": "TS"},
    "SD2225": {"primitive": "delete_row", "params": {"filter_field": "TSPARMCD", "filter_value": "ADAPT"}, "domain": "TS"},
    "SD2226": {"primitive": "delete_row", "params": {"filter_field": "TSPARMCD", "filter_value": "DCUTDTC"}, "domain": "TS"},
    "SD2227": {"primitive": "delete_row", "params": {"filter_field": "TSPARMCD", "filter_value": "DCUTDESC"}, "domain": "TS"},
    "SD2228": {"primitive": "delete_row", "params": {"filter_field": "TSPARMCD", "filter_value": "INTMODEL"}, "domain": "TS"},
    "SD2229": {"primitive": "delete_row", "params": {"filter_field": "TSPARMCD", "filter_value": "NARMS"}, "domain": "TS"},
    "SD2230": {"primitive": "delete_row", "params": {"filter_field": "TSPARMCD", "filter_value": "STYPE"}, "domain": "TS"},
    "SD2231": {"primitive": "delete_row", "params": {"filter_field": "TSPARMCD", "filter_value": "INTTYPE"}, "domain": "TS"},
    "SD2232": {"primitive": "delete_row", "params": {"filter_field": "TSPARMCD", "filter_value": "SSTDTC"}, "domain": "TS"},
    "SD2233": {"primitive": "delete_row", "params": {"filter_field": "TSPARMCD", "filter_value": "SENDTC"}, "domain": "TS"},
    "SD2234": {"primitive": "delete_row", "params": {"filter_field": "TSPARMCD", "filter_value": "ACTSUB"}, "domain": "TS"},
    "SD2235": {"primitive": "delete_row", "params": {"filter_field": "TSPARMCD", "filter_value": "HLTSUBJI"}, "domain": "TS"},
    "SD2273": {"primitive": "delete_row", "params": {"filter_field": "TSPARMCD", "filter_value": "EXTTIND"}, "domain": "TS"},
    "SD2274": {"primitive": "delete_row", "params": {"filter_field": "TSPARMCD", "filter_value": "NCOHORT"}, "domain": "TS"},
    "SD2275": {"primitive": "delete_row", "params": {"filter_field": "TSPARMCD", "filter_value": "OBJSEC"}, "domain": "TS"},
    "SD2276": {"primitive": "delete_row", "params": {"filter_field": "TSPARMCD", "filter_value": "PDPSTIND"}, "domain": "TS"},
    "SD2277": {"primitive": "delete_row", "params": {"filter_field": "TSPARMCD", "filter_value": "PDSTIND"}, "domain": "TS"},
    "SD2278": {"primitive": "delete_row", "params": {"filter_field": "TSPARMCD", "filter_value": "PIPIND"}, "domain": "TS"},
    "SD2279": {"primitive": "delete_row", "params": {"filter_field": "TSPARMCD", "filter_value": "RDIND"}, "domain": "TS"},
    "SD2280": {"primitive": "delete_row", "params": {"filter_field": "TSPARMCD", "filter_value": "SDTIGVER"}, "domain": "TS"},
    "SD2281": {"primitive": "delete_row", "params": {"filter_field": "TSPARMCD", "filter_value": "SDTMVER"}, "domain": "TS"},
    "SD2282": {"primitive": "delete_row", "params": {"filter_field": "TSPARMCD", "filter_value": "THERAREA"}, "domain": "TS"},
    "SD0001": {"primitive": "delete_row", "params": {"filter_field": None, "filter_value": None}, "domain": "--"},

    # ========== TS rules: duplicate_record ==========
    "SD1214": {"primitive": "duplicate_record", "params": {"key_fields": ["TSPARMCD"], "filter_field": "TSPARMCD", "filter_value": "ADDON"}, "domain": "TS"},
    "SD1216": {"primitive": "duplicate_record", "params": {"key_fields": ["TSPARMCD"], "filter_field": "TSPARMCD", "filter_value": "AGEMAX"}, "domain": "TS"},
    "SD1218": {"primitive": "duplicate_record", "params": {"key_fields": ["TSPARMCD"], "filter_field": "TSPARMCD", "filter_value": "AGEMIN"}, "domain": "TS"},
    "SD1220": {"primitive": "duplicate_record", "params": {"key_fields": ["TSPARMCD"], "filter_field": "TSPARMCD", "filter_value": "LENGTH"}, "domain": "TS"},
    "SD1222": {"primitive": "duplicate_record", "params": {"key_fields": ["TSPARMCD"], "filter_field": "TSPARMCD", "filter_value": "PLANSUB"}, "domain": "TS"},
    "SD1224": {"primitive": "duplicate_record", "params": {"key_fields": ["TSPARMCD"], "filter_field": "TSPARMCD", "filter_value": "RANDOM"}, "domain": "TS"},
    "SD1225": {"primitive": "duplicate_record", "params": {"key_fields": ["TSPARMCD"], "filter_field": "TSPARMCD", "filter_value": "SEXPOP"}, "domain": "TS"},
    "SD1227": {"primitive": "duplicate_record", "params": {"key_fields": ["TSPARMCD"], "filter_field": "TSPARMCD", "filter_value": "NARMS"}, "domain": "TS"},
    "SD1038": {"primitive": "duplicate_record", "params": {"key_fields": ["TSSEQ", "TSPARMCD"]}, "domain": "TS"},

    # ========== TS rules: set_invalid_value ==========
    "SD1215": {"primitive": "set_invalid_value", "params": {"field": "TSVAL", "value": "INVALID", "filter_field": "TSPARMCD", "filter_value": "AGEMAX"}, "domain": "TS"},
    "SD1217": {"primitive": "set_invalid_value", "params": {"field": "TSVAL", "value": "INVALID", "filter_field": "TSPARMCD", "filter_value": "AGEMIN"}, "domain": "TS"},
    "SD1219": {"primitive": "set_invalid_value", "params": {"field": "TSVAL", "value": "INVALID", "filter_field": "TSPARMCD", "filter_value": "LENGTH"}, "domain": "TS"},
    "SD1221": {"primitive": "set_invalid_value", "params": {"field": "TSVAL", "value": "INVALID", "filter_field": "TSPARMCD", "filter_value": "PLANSUB"}, "domain": "TS"},
    "SD1223": {"primitive": "set_invalid_value", "params": {"field": "TSVAL", "value": "INVALID", "filter_field": "TSPARMCD", "filter_value": "RANDOM"}, "domain": "TS"},
    "SD1269": {"primitive": "set_invalid_value", "params": {"field": "TSVAL", "value": "2.5", "filter_field": "TSPARMCD", "filter_value": "RANDQT"}, "domain": "TS"},
    "SD1295": {"primitive": "set_invalid_value", "params": {"field": "TSVAL", "value": "INVALID", "filter_field": "TSPARMCD", "filter_value": "ADDON"}, "domain": "TS"},
    "SD1296": {"primitive": "set_invalid_value", "params": {"field": "TSVAL", "value": "INVALID", "filter_field": "TSPARMCD", "filter_value": "ADAPT"}, "domain": "TS"},
    "SD1323": {"primitive": "set_invalid_value", "params": {"field": "TSVAL", "value": "INVALID_COUNTRY", "filter_field": "TSPARMCD", "filter_value": "FCNTRY"}, "domain": "TS"},
    "SD2245": {"primitive": "set_invalid_value", "params": {"field": "TSVAL", "value": "INVALID_DATE", "filter_field": "TSPARMCD", "filter_value": "DCUTDTC"}, "domain": "TS"},
    "SD2246": {"primitive": "set_invalid_value", "params": {"field": "TSVAL", "value": "INVALID", "filter_field": "TSPARMCD", "filter_value": "NARMS"}, "domain": "TS"},
    "SD2247": {"primitive": "set_invalid_value", "params": {"field": "TSVAL", "value": "INVALID_DATE", "filter_field": "TSPARMCD", "filter_value": "SSTDTC"}, "domain": "TS"},
    "SD2248": {"primitive": "set_invalid_value", "params": {"field": "TSVAL", "value": "INVALID_DATE", "filter_field": "TSPARMCD", "filter_value": "SENDTC"}, "domain": "TS"},
    "SD2249": {"primitive": "set_invalid_value", "params": {"field": "TSVAL", "value": "INVALID", "filter_field": "TSPARMCD", "filter_value": "ACTSUB"}, "domain": "TS"},
    "SD2250": {"primitive": "set_invalid_value", "params": {"field": "TSVAL", "value": "INVALID", "filter_field": "TSPARMCD", "filter_value": "CURTRT"}, "domain": "TS"},
    "SD2253": {"primitive": "set_invalid_value", "params": {"field": "TSVAL", "value": "INVALID", "filter_field": "TSPARMCD", "filter_value": "COMPTRT"}, "domain": "TS"},
    "SD2257": {"primitive": "set_invalid_value", "params": {"field": "TSVAL", "value": "INVALID", "filter_field": "TSPARMCD", "filter_value": "INDIC"}, "domain": "TS"},
    "SD2258": {"primitive": "set_invalid_value", "params": {"field": "TSVALCD", "value": "INVALID", "filter_field": "TSPARMCD", "filter_value": "INDIC"}, "domain": "TS"},
    "SD2260": {"primitive": "set_invalid_value", "params": {"field": "TSVAL", "value": "INVALID", "filter_field": "TSPARMCD", "filter_value": "TRT"}, "domain": "TS"},
    "SD2261": {"primitive": "set_invalid_value", "params": {"field": "TSVALCD", "value": "INVALID", "filter_field": "TSPARMCD", "filter_value": "TRT"}, "domain": "TS"},
    "SD2263": {"primitive": "set_invalid_value", "params": {"field": "TSVAL", "value": "INVALID", "filter_field": "TSPARMCD", "filter_value": "PCLAS"}, "domain": "TS"},
    "SD2264": {"primitive": "set_invalid_value", "params": {"field": "TSVALCD", "value": "INVALID", "filter_field": "TSPARMCD", "filter_value": "PCLAS"}, "domain": "TS"},
    "SD2267": {"primitive": "set_invalid_value", "params": {"field": "TSVAL", "value": "INVALID", "filter_field": "TSPARMCD", "filter_value": "TDIGRP"}, "domain": "TS"},
    "SD2268": {"primitive": "set_invalid_value", "params": {"field": "TSVALCD", "value": "INVALID", "filter_field": "TSPARMCD", "filter_value": "TDIGRP"}, "domain": "TS"},

    # ========== TS rules: mismatch_pair ==========
    "SD2252": {"primitive": "mismatch_pair", "params": {"field_a": "TSVAL", "field_b": "TSVALCD", "filter_field": "TSPARMCD", "filter_value": "CURTRT"}, "domain": "TS"},
    "SD2254": {"primitive": "mismatch_pair", "params": {"field_a": "TSVAL", "field_b": "TSVALCD", "filter_field": "TSPARMCD", "filter_value": "COMPTRT"}, "domain": "TS"},
    "SD2255": {"primitive": "mismatch_pair", "params": {"field_a": "TSVAL", "field_b": "TSVALCD", "filter_field": "TSPARMCD", "filter_value": "COMPTRT"}, "domain": "TS"},
    "SD2259": {"primitive": "mismatch_pair", "params": {"field_a": "TSVAL", "field_b": "TSVALCD", "filter_field": "TSPARMCD", "filter_value": "INDIC"}, "domain": "TS"},
    "SD2262": {"primitive": "mismatch_pair", "params": {"field_a": "TSVAL", "field_b": "TSVALCD", "filter_field": "TSPARMCD", "filter_value": "TRT"}, "domain": "TS"},
    "SD2265": {"primitive": "mismatch_pair", "params": {"field_a": "TSVAL", "field_b": "TSVALCD", "filter_field": "TSPARMCD", "filter_value": "PCLAS"}, "domain": "TS"},
    "SD2269": {"primitive": "mismatch_pair", "params": {"field_a": "TSVAL", "field_b": "TSVALCD", "filter_field": "TSPARMCD", "filter_value": "TDIGRP"}, "domain": "TS"},
    "SD2251": {"primitive": "mismatch_pair", "params": {"field_a": "TSVAL", "field_b": "TSVALCD", "filter_field": "TSPARMCD", "filter_value": "CURTRT"}, "domain": "TS"},

    # ========== TS rules: blank_field / populate_forbidden ==========
    "SD1260": {"primitive": "blank_field", "params": {"field": "TSVCDVER"},
               "domain": "TS", "guard": "TSVCDREF != "},
    "SD1306": {"primitive": "blank_field",
               "params": {"field": "TSVAL", "filter_field": "TSPARMCD", "filter_value": "TDIGRP"},
               "domain": "TS"},
    "SD1307": {"primitive": "blank_field",
               "params": {"field": "TSVAL", "filter_field": "TSPARMCD", "filter_value": "TDIGRP"},
               "domain": "TS"},
    "SD1308": {"primitive": "blank_field",
               "params": {"field": "TSVAL", "filter_field": "TSPARMCD", "filter_value": "CURTRT"},
               "domain": "TS"},
    "SD1309": {"primitive": "blank_field",
               "params": {"field": "TSVAL", "filter_field": "TSPARMCD", "filter_value": "TRT"},
               "domain": "TS"},
    "SD1310": {"primitive": "blank_field",
               "params": {"field": "TSVAL", "filter_field": "TSPARMCD", "filter_value": "INTMODEL"},
               "domain": "TS"},
    "SD1311": {"primitive": "blank_field",
               "params": {"field": "TSVAL", "filter_field": "TSPARMCD", "filter_value": "INTTYPE"},
               "domain": "TS"},
    "SD1312": {"primitive": "blank_field",
               "params": {"field": "TSVAL", "filter_field": "TSPARMCD", "filter_value": "PCLAS"},
               "domain": "TS"},
    "SD2017": {"primitive": "blank_field", "params": {"field": "TSVAL"}, "domain": "TS"},
    "SD2018": {"primitive": "populate_forbidden",
               "params": {"field": "TSVALNF", "value": "NINF"},
               "domain": "TS", "guard": "TSVAL != "},
    "SD1297": {"primitive": "populate_forbidden",
               "params": {"field": "TSVAL", "value": "NINF"},
               "domain": "TS"},
    "SD1268": {"primitive": "mismatch_pair",
               "params": {"field_a": "TSVCDVER", "field_b": "TSVCDREF"}, "domain": "TS"},

    # ========== TS: set_invalid_value for TSVCDREF ==========
    "SD2240": {"primitive": "set_invalid_value", "params": {"field": "TSVCDREF", "value": "INVALID_REF", "filter_field": "TSPARMCD", "filter_value": "INDIC"}, "domain": "TS"},
    "SD2241": {"primitive": "set_invalid_value", "params": {"field": "TSVCDREF", "value": "INVALID_REF", "filter_field": "TSPARMCD", "filter_value": "CURTRT"}, "domain": "TS"},
    "SD2242": {"primitive": "set_invalid_value", "params": {"field": "TSVCDREF", "value": "INVALID_REF", "filter_field": "TSPARMCD", "filter_value": "TRT"}, "domain": "TS"},
    "SD2243": {"primitive": "set_invalid_value", "params": {"field": "TSVCDREF", "value": "INVALID_REF", "filter_field": "TSPARMCD", "filter_value": "PCLAS"}, "domain": "TS"},
    "SD2244": {"primitive": "set_invalid_value", "params": {"field": "TSVCDREF", "value": "INVALID_REF", "filter_field": "TSPARMCD", "filter_value": "FCNTRY"}, "domain": "TS"},
    "SD2256": {"primitive": "set_invalid_value", "params": {"field": "TSVCDREF", "value": "INVALID_REF", "filter_field": "TSPARMCD", "filter_value": "COMPTRT"}, "domain": "TS"},
    "SD2266": {"primitive": "set_invalid_value", "params": {"field": "TSVCDREF", "value": "INVALID_REF", "filter_field": "TSPARMCD", "filter_value": "TDIGRP"}, "domain": "TS"},
    "SD2283": {"primitive": "invalid_codelist",
               "params": {"field": "TSVALNF", "valid_values": ["NINF", "PINF", "UNK", "NI", "NA", "NASK", "TRC", "MSK", "OTH"]},
               "domain": "TS"},

    # ========== codelist rules ==========
    "CT2001": {"primitive": "invalid_codelist",
               "params": {"field": "AGEU", "valid_values": ["YEARS", "MONTHS", "WEEKS", "DAYS", "HOURS"]},
               "domain": "DM"},
    "CT2002": {"primitive": "invalid_codelist",
               "params": {"field": "EPOCH", "valid_values": ["SCREENING", "TREATMENT", "FOLLOW-UP", "RUN-IN", "WASHOUT"]},
               "domain": "--"},
    "CT2003": {"primitive": "mismatch_pair",
               "params": {"field_a": "EPOCH", "field_b": "EPOCHC"}, "domain": "--"},

    # ========== PP domain (auto-skipped at runtime) ==========
    "SD1348": {"primitive": "blank_field", "params": {"field": "--STINT"}, "domain": "PP"},
    "SD1350": {"primitive": "blank_field", "params": {"field": "--ENINT"},
               "domain": "PP", "guard": "--STINT != "},
    "SD1351": {"primitive": "blank_field", "params": {"field": "--STINT"},
               "domain": "PP", "guard": "--ENINT != "},

    # ========== TM domain (auto-skipped at runtime) ==========
    "SD1355": {"primitive": "drop_domain", "params": {"domain": "TM"}},
    "SD1356": {"primitive": "drop_domain", "params": {"domain": "TM"}},

    # ========== DI/TS PARM rules ==========
    "SD0019": {"primitive": "set_invalid_value",
               "params": {"field": "TSPARM", "value": "INVALID PARM LABEL 999"},
               "domain": "TS"},
    "SD0020": {"primitive": "set_invalid_value",
               "params": {"field": "TSPARMCD", "value": "INVPRMCD99"},
               "domain": "TS"},
    "SD0021": {"primitive": "blank_field", "params": {"field": "--ENDTC"},
               "domain": "--", "guard": "--STDTC != "},

    # ========== MB domain (auto-skipped at runtime) ==========
    "SD1263": {"primitive": "blank_field", "params": {"field": "MBRESCAT"},
               "domain": "MB", "guard": "MBTESTCD == ORGANISM"},

    # ========== TR/RS/TU domains (auto-skipped at runtime) ==========
    "SD1336": {"primitive": "cross_domain_mismatch",
               "params": {"source": "TR", "source_field": "TRLNKID",
                          "target": "TU", "target_field": "TULNKID",
                          "mismatch_type": "not_in_set"},
               "domain": "TR"},
    "SD1337": {"primitive": "cross_domain_mismatch",
               "params": {"source": "RS", "source_field": "RSLNKID",
                          "target": "TR", "target_field": "TRLNKID",
                          "mismatch_type": "not_in_set"},
               "domain": "RS"},
    "SD1338": {"primitive": "cross_domain_mismatch",
               "params": {"source": "RS", "source_field": "RSLNKGRP",
                          "target": "TR", "target_field": "TRLNKGRP",
                          "mismatch_type": "not_in_set"},
               "domain": "RS"},

    # ========== skipped rules (not injectable) ==========
    # SD1071: dataset > 5 GB — not feasible
    # SD9999: dataset class not recognized — meta-level
    # SD0062: incompatible data source — meta-level
    # SD1119: CO domain not generated
    # SD1368: SM domain not generated
    # SD1008: CO domain not generated
    # SD1065: CO domain not generated
    # SD1301: TD domain not generated
    # SD1233: DI domain not generated
}


# Canonical category universe (26) from config/injection/defaults.yaml profiles.all
ALL_CATEGORIES = [
    "dm_date",
    "date_cross_domain",
    "age_arm",
    "dm_cross_domain",
    "special_purpose",
    "interventions",
    "ae_events",
    "events",
    "findings_individual",
    "findings_chain_1",
    "findings_chain_2",
    "general_obs_1",
    "general_obs_2",
    "relationship",
    "ts_domain",
    "ts_parmcd_req",
    "ts_parmcd_limit",
    "ts_tsval",
    "trial_design",
    "mandatory_domain",
    "mandatory_variable",
    "mandatory_variable_2",
    "custom_split",
    "all_domains_1",
    "all_domains_2",
    "device",
]


def _infer_fallback_category(rule_def: dict) -> str:
    """Infer a stable fallback category from rule metadata (non-regex)."""
    primitive = rule_def.get("primitive", "")
    domain = rule_def.get("domain", "")
    params = rule_def.get("params", {}) or {}
    field = str(params.get("field", ""))
    source_field = str(params.get("source_field", ""))
    target_field = str(params.get("target_field", ""))
    guard = str(rule_def.get("guard", ""))

    # 1) Structural categories
    if primitive == "drop_domain":
        return "mandatory_domain"
    if primitive == "drop_column":
        col = str(params.get("column", ""))
        if col in {"--TPTREF", "--LOC", "--PRESP", "--STINT", "--ENINT", "MIDS"}:
            return "mandatory_variable_2"
        return "mandatory_variable"
    if primitive == "add_column":
        if domain == "AE":
            return "all_domains_2"
        return "all_domains_1"
    if primitive == "reorder_columns":
        return "custom_split"

    # 2) TS categories
    if domain == "TS" and primitive == "delete_row":
        return "ts_parmcd_req"
    if domain == "TS" and primitive == "duplicate_record":
        return "ts_parmcd_limit"
    if domain == "TS" and primitive == "set_invalid_value":
        if field in {"TSVAL", "TSVALCD", "TSVCDREF"}:
            return "ts_tsval"
        return "ts_domain"
    if domain == "TS":
        return "ts_domain"

    # 3) Device-oriented categories
    if domain in {"DI", "DU", "DO", "MB", "PP"}:
        return "device"
    if any(key in {"SPDEVID", "DIPARMCD", "MBRESCAT"} for key in [field, source_field, target_field]):
        return "device"

    # 4) DM core categories
    if domain == "DM" and primitive in {"blank_field", "invert_date_order", "populate_forbidden"}:
        dm_date_fields = {"RFSTDTC", "RFENDTC", "RFXSTDTC", "RFXENDTC", "RFICDTC", "DTHDTC", "DTHFL", "AGE"}
        if field in dm_date_fields or params.get("start_field") in dm_date_fields or params.get("end_field") in dm_date_fields:
            return "dm_date"
    if domain == "DM" and primitive in {"mismatch_pair", "set_invalid_value", "invalid_codelist"}:
        return "age_arm"
    if domain == "DM" and primitive in {"cross_domain_mismatch", "cross_domain_orphan", "duplicate_record"}:
        return "dm_cross_domain"

    # 5) Cross-domain date and findings chains
    if primitive in {"wrong_derived", "truncate_with_derived"}:
        return "date_cross_domain"
    if primitive == "invert_date_order" and domain == "--":
        return "date_cross_domain"
    if primitive == "cross_domain_mismatch" and domain in {"DM", "--"}:
        if any(token in (source_field + target_field + field) for token in ["DTC", "DY", "STDTC", "ENDTC", "RFPENDTC"]):
            return "date_cross_domain"
        return "dm_cross_domain"

    if "--" in {domain, str(params.get("source", ""))}:
        combined = ",".join([
            field,
            source_field,
            target_field,
            str(params.get("date_field", "")),
            str(params.get("dy_field", "")),
        ])
        if any(token in combined for token in ["ORRES", "STRES", "TEST", "RESCAT", "BLFL", "LOBXFL"]):
            if any(token in combined for token in ["BLFL", "LOBXFL"]):
                return "findings_chain_2"
            if any(token in combined for token in ["DTC", "DY", "ENDTC"]):
                return "findings_chain_1"
            return "findings_individual"

    # 6) Events / interventions / relationship / general observations
    death_tokens = {"DTHFL", "DTHDTC", "FATAL", "DEATH", "DEAD"}
    if domain in {"AE", "DS", "SS", "DD"} and (
        any(token in (source_field + target_field + field) for token in death_tokens)
        or str(params.get("source_value", "")) in death_tokens
        or str(params.get("expected_target", "")) in death_tokens
    ):
        return "ae_events"

    if domain in {"AE", "DS", "MH", "DV", "EX"}:
        return "events"

    if domain in {"EX", "EC", "CM", "PC"} or any(token in (field + source_field + target_field) for token in ["DOSE", "TRT", "OCCUR", "PRESP"]):
        return "interventions"

    if domain in {"RELREC", "SUPPQUAL"}:
        return "relationship"

    if any(token in (field + source_field + target_field + guard) for token in ["VISIT", "VISITNUM", "TPT", "TPTNUM", "EPOCH"]):
        if "EPOCH" in (field + source_field + target_field + guard):
            return "general_obs_2"
        return "general_obs_1"

    # 7) Trial design and special purpose
    if domain in {"TA", "TE", "TI", "TV", "SV", "SE", "IE"}:
        return "trial_design"

    return "special_purpose"


def _enrich_categories_from_catalog() -> None:
    """Populate category for every rule using catalog lookup first, then fallback."""
    try:
        from injection.catalog import RULE_PRIMITIVE_MAP as CATALOG_RULE_MAP
    except Exception:
        CATALOG_RULE_MAP = {}

    for rule_id, rule_def in RULE_PRIMITIVE_MAP.items():
        if "category" in rule_def and str(rule_def.get("category", "")).strip():
            continue

        catalog_def = CATALOG_RULE_MAP.get(rule_id, {})
        category = str(catalog_def.get("category", "")).strip()
        if category:
            rule_def["category"] = category
        else:
            rule_def["category"] = _infer_fallback_category(rule_def)

        if rule_def["category"] not in ALL_CATEGORIES:
            rule_def["category"] = "special_purpose"


def _build_category_index() -> dict:
    """Build category -> rule list index while preserving all 26 category keys."""
    index = {category: [] for category in ALL_CATEGORIES}
    for rule_id, rule_def in RULE_PRIMITIVE_MAP.items():
        category = str(rule_def.get("category", "")).strip()
        if category in index:
            index[category].append(rule_id)
    return index


_enrich_categories_from_catalog()

# Exposed index that always contains all 26 categories as keys.
CATEGORY_RULE_INDEX = _build_category_index()
